# action.yml
name: 'IPS Resource Updater'
description: 'Update a resource on IPS Community Forum'
inputs:
  IPS_URL:
    description: 'URL of the IPS board.'
    required: true
  API_KEY:
    description: 'API key to access the IPS board.'
    required: true
  RESOURCE_ID:  # id of input
    description: 'ID of the resource to update'
    required: true
  FILE_NAME:
    description: 'File Name of the file to link to this resource.'
    required: true
  FILE_URL:
    description: 'External URL of the file to link to this resource.'
    required: true
  VERSION:
    description: 'New version of the resource.'
    default: '1.0.0'
    required: false
  CHANGELOG:
    description: 'Changelog for this version.'
    required: false
    default: ''
  CHANGELOG_FILE:
    description: 'Changelog file for this version.'
    required: false
    default: ''
  
runs:
  using: 'docker'
  image: 'Dockerfile'
  env: 
    IPS_URL: ${{ inputs.ips_url }}
    API_KEY: ${{ inputs.api_key }}
    RESOURCE_ID: ${{ inputs.resource_id }}
    FILE_NAME: ${{ inputs.file_name }}
    FILE_URL: ${{ inputs.file_url }}
    VERSION: ${{ inputs.version }}
    CHANGELOG: ${{ inputs.changelog }}
    CHANGELOG_FILE: ${{ inputs.changelog_file }}
