# action.yml
name: 'IPS Resource Updater'
description: 'Update a resource on IPS Community Forum'
inputs:
  ips_url:
    description: 'URL of the IPS board.'
    required: true
  api_key:
    description: 'API key to access the IPS board.'
    required: true
  resource_id:  # id of input
    description: 'ID of the resource to update'
    required: true
  file_url:
    description: 'External URL of the file to link to this resource.'
    required: true
  version:
    description: 'New version of the resource.'
    required: true
  changelog:
    description: 'Changelog for this version.'
    required: false
    default: ''
  save_previous:
    description: 'Save the previous version of this resource.'
    required: false
    default: 'false'
  
runs:
  using: 'docker'
  image: 'Dockerfile'
  env: 
    ips_url: ${{ inputs.ips_url }}
    api_key: ${{ inputs.api_key }}
    resource_id: ${{ inputs.resource_id }}
    file_url: ${{ inputs.file_url }}
    version: ${{ inputs.version }}
    changelog: ${{ inputs.changelog }}
    save_previous: ${{ inputs.save_previous }}